apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  ports:
  {{- with .Values.service }}
  - port: {{ .internalPort }}
    protocol: TCP
    nodePort: {{ .externalPort }}
  type: {{ .type }}
  {{- end }}
  selector:
    run: {{ template "fullname" . }}